apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskdemoapp
  template:
    metadata:
      labels:
        app: flaskdemoapp
    spec:
      containers:
      - name: springboot-container
        image: atozdevopstraining/flaskdemoapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        

