apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"  # For NLB use "nlb"
spec:
  selector:
    app: flaskdemoapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
